### ISSUE TITLE
Pulse graph is wrongly labeled as "ECCO"

### ISSUE THREAD

**Issue by ehrhart** [Odeuropa/knowledge-graph#11]
The graph http://data.odeuropa.eu/pulse has its label set to "ECCO" instead of "Pulse", as seen in this file:

https://github.com/Odeuropa/knowledge-graph/blob/f3b2e33667eed66bc512adeef9c84bfe64317194/dump/pulse/graph.ttl#L6

**Comment by pasqLisena** [comment]
fixed directly on the graph online
